[package]
name = "abc279"
version = "0.1.0"
edition = "2021"
#lto = true
#panic = 'abort'

# dependencies added to new project
[dependencies]
proconio = "*"
itertools = "*"
num = "*"

[profile.release]
